### ISSUE TITLE
docker image for config server seems to be broken

### ISSUE THREAD

**Issue by nbyl** [codecentric/event-driven-microservices-platform#6]
Hi,

the image on Docker Hub issued on 2016-05-29T09:25:29.072Z seems to broken. Whenever I try to start it, only the following message will be output:

```
Error: Invalid or corrupt jarfile spring-cloud-config-server-1.1.0.RELEASE-exec.jar
```

Greetings,

Nicolas

**Comment by tobiasflohre** [comment]
Yes, the reason is that from version 1.1.0.RELEASE Spring Cloud Config doesn't provide an executable server jar anymore. We have to build it ourselves now. I fixed that seven days ago.
